"""Report generation — CSV and Markdown output for audit risk scan results."""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

import pandas as pd


def write_csv(
    df: pd.DataFrame,
    path: str,
    top_n: int | None = None,
) -> None:
    """Write classified audit opinions to CSV.

    Args:
        df: DataFrame with risk_level, risk_label, and context columns.
        path: Output file path.
        top_n: If set, only write top-N rows (by risk_level desc, then symbol).
    """
    out = df.copy()
    if top_n is not None and len(out) > top_n:
        out = out.sort_values(
            ["risk_level", "symbol"], ascending=[False, True]
        ).head(top_n)

    Path(path).parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(path, index=False, encoding="utf-8-sig")
    print(f"[ok] wrote {path} ({len(out)} rows)", file=sys.stderr)


def write_markdown(
    df: pd.DataFrame,
    path: str,
    quarter: str = "",
    top_n: int | None = None,
    meta: dict | None = None,
) -> None:
    """Write a human-readable Markdown audit risk report.

    Args:
        df: Classified DataFrame.
        path: Output file path.
        quarter: Target quarter label for the report title.
        top_n: If set, limit to top-N by risk (desc).
        meta: Optional dict with summary stats (from rules.summarize()).
    """
    out = df.copy()
    if top_n is not None and len(out) > top_n:
        out = out.sort_values(
            ["risk_level", "symbol"], ascending=[False, True]
        ).head(top_n)

    Path(path).parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    title = f"# 审计意见风险扫描报告 · {quarter}" if quarter else "# 审计意见风险扫描报告"
    lines.append(title)
    lines.append("")
    lines.append(f"**扫描时间**: {_now_iso()}")
    if meta:
        lines.append("")
        lines.append("## 概览")
        lines.append("")
        lines.append(f"| 指标 | 值 |")
        lines.append(f"|---|---|")
        lines.append(f"| 总记录数 | {meta.get('total', 0)} |")
        lines.append(f"| 低风险 | {meta.get('low', 0)} |")
        lines.append(f"| 中风险 | {meta.get('medium', 0)} |")
        lines.append(f"| 高风险 | {meta.get('high', 0)} |")
        lines.append(f"| 严重风险 | {meta.get('critical', 0)} |")
        lines.append(f"| 需人工确认 | {meta.get('unknown', 0)} |")

        unknown_op = meta.get("unknown_opinions", [])
        if unknown_op:
            lines.append("")
            lines.append("### ⚠️ 未知审计意见类型（需补充映射）")
            for op in unknown_op:
                lines.append(f"- `{op}`")

    lines.append("")
    lines.append("## 风险清单")
    lines.append("")

    if out.empty:
        lines.append("✅ 未发现高风险审计意见。")
    else:
        # Build the table
        display_cols = ["symbol", "name", "quarter", "date", "agency",
                        "audit_type", "opinion", "risk_label"]
        available = [c for c in display_cols if c in out.columns]
        lines.append(f"| {' | '.join(available)} |")
        lines.append(f"|{'|'.join(['---'] * len(available))}|")
        for _, row in out.iterrows():
            vals = [str(row[c]) if pd.notna(row[c]) else "" for c in available]
            lines.append(f"| {' | '.join(vals)} |")

    lines.append("")
    lines.append("---")
    lines.append(f"*Report generated by skill-audit-opinion-scanner*")

    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[ok] wrote {path}", file=sys.stderr)


def _now_iso() -> str:
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
